#!/bin/bash
VERSION="v0.5 20501"


if [ -f  "$HOME/.config/rclonesync/telegram" ]
then
source  ~/.config/rclonesync/telegram
else
echo""
echo "Añade el Token e ID de Telegram, para que te notifique en caso de mala sincronización"
echo "Introduce el comando:"
echo ""
echo -e "\e[3m  rclonesyncstate t nombre_nube\e[0m"
echo ""
echo ""
fi

if [ "$1" = "-h" ] ||  [ "$1" = "--help" ] ||  [ "$1" = "" ]
then
echo "rclonesyncstate                                                                                                                                                                                                  
                    OPCIÓN             SIGNIFICADO                                                                                                                                                                 
rclonesyncstate    e  [nube]      ->  Mira si hay un error. En caso que así sea, envia una notificación                                                                                                         
rclonesyncstate    fs [nube]      ->  First-Sync                                                                                                                                                                 
rclonesyncstate    n  [nube]      ->  Añade el comando hacia la nube                                                                                                                                             
rclonesyncstate    l  [logs]      ->  Añade el comando hacia la nube
rclonesyncstate    t              ->  Añade Token e ID de telegram 
rclonesyncstate    i              ->  Instalar o actualizar rclonesync. Ejecutar como sudo 
rclonesyncstate    tt [texto]     ->  Mensaje de prueba a Telegram
rclonesyncstate   -h              ->  Ayuda                                                                                                                                                                       
                                                                                                                                                                                                                 
rclonesyncstate. $VERSION                                                                                                                                                                                        
                   
"
fi

if [ "$1" = "t" ]
then
echo "Vamos añadir el Token e ID de Telegram donde vas a recibir las notifiaciones"    
echo ""
echo -en " Token: "
read TOKEN
echo -en " ID: "
read ID
echo -en "TOKEN='"$TOKEN"'\nID='"$ID"'" >  ~/.config/rclonesync/telegram
fi

if [ "$1" = "i" ]
then
sudo curl -L https://raw.githubusercontent.com/cjnaz/rclonesync-V2/master/rclonesync.py -o /usr/bin/rclonesync && sudo chmod +x /usr/bin/rclonesync
echo "actualizado"
exit
fi

if [ "$1" = "fs" ]
then
/bin/bash ~/.config/rclonesync/$2
echo ""
echo -e "\e[4mAñade a tu cron con crontab -e\e[0m"
echo ""
echo "*/2 * * * * $(cat ~/.config/rclonesync/$2 | sed s'|--first-sync||'g)"
echo "*/10 * * * * /usr/bin/rclonesyncstate e $2"
echo ""
echo ""
echo -e "\e[4mLog de rclonesync\e[0m"
cat  ~/.config/rclonesync/log_$2 | tail -n2
echo ""
fi

if [ "$1" = "e" ]
then
ERROR=$(cat  ~/.config/rclonesync/log_$2 | tail -n5 | grep "Error")   
if [ "$ERROR" != "" ]
then
echo "ERROR"
curl -X POST https://api.telegram.org/bot$TOKEN/sendMessage\?chat_id\=$ID\&text\="Error de Sincronización con la nube $2 en $(hostname)"
fi
fi

if [ "$1" = "tt" ]
then
curl -X POST https://api.telegram.org/bot$TOKEN/sendMessage\?chat_id\=$ID\&text\="$2"
fi

if [ "$1" = "n" ]
then
mkdir -p ~/.config/rclonesync/
echo -en "Ruta local: "
read LOCAL
echo -en "Ruta en rclone: "
read RCLONE
echo "/usr/bin/rclonesync  "$LOCAL" "$RCLONE" --verbose --first-sync >> ~/.config/rclonesync/log_"$2" 2>&1" > ~/.config/rclonesync/$2
echo $(cat ~/.config/rclonesync/$2 | sed s'|--first-sync|--force|'g) > ~/.config/rclonesync/force.$2
echo " "
fi

if [ "$1" = "f" ]
then
/bin/bash  ~/.config/rclonesync/force.$2
echo ""
echo -e "\e[4mLog de rclonesync\e[0m"
cat  ~/.config/rclonesync/log_$2 | tail -n2
fi

if [ "$1" = "l" ]
then
cat  ~/.config/rclonesync/log_$2
fi
